--- #YAML:1.0
name:               AnyEvent-Curl-Multi
version:            1.0
abstract:           a fast event-driven HTTP client
author:
    - Michael S. Fischer <michael+cpan@dynamine.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:        5
    HTTP::Request:   0
    HTTP::Response:  0
    Object::Event:   1
    Test::More:      0
    WWW::Curl:       4.14
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
